#pragma once

#define IS_MATH21

#define MATH21_FLAG_RELEASE
/* #undef MATH21_FLAG_USE_CUDA */
#define MATH21_FLAG_USE_OPENMP
/* #undef MATH21_FLAG_IS_WIN32 */
/* #undef MATH21_FLAG_IS_ANDROID */
/* #undef MATH21_FLAG_IS_APPLE */
#define MATH21_FLAG_IS_LINUX
